### ISSUE TITLE
Failed to load the api-docs package

### ISSUE THREAD

**Issue by micahscopes** [sharvil/api-docs#25] opened 2016-02-12 17:26 UTC
This is what I get as soon as I install the api-docs package and it attempts to load.

**Atom Version**: 0.188.0
**System**: linux 3.19.0-39-generic
**Thrown From**: [api-docs](https://github.com/sharvil/api-docs) package, v0.0.4

### Stack Trace

Failed to load the api-docs package

```
At /home/micah/.atom/packages/api-docs/src/main.js: Unexpected token (12:29)
  10 | 
  11 | class Application {
> 12 |   static LAZY_LOAD_DELAY_MS_ = 3000;
     |                              ^
  13 | 
  14 |   constructor() {
  15 |     this.subscriptions_ = new CompositeDisposable();

SyntaxError: /home/micah/.atom/packages/api-docs/src/main.js: Unexpected token (12:29)
  10 | 
  11 | class Application {
> 12 |   static LAZY_LOAD_DELAY_MS_ = 3000;
     |                              ^
  13 | 
  14 |   constructor() {
  15 |     this.subscriptions_ = new CompositeDisposable();
    at raise (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:343:15)
    at unexpected (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:2278:5)
    at expect (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:2266:18)
    at parseFunctionParams (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:3571:5)
    at parseMethod (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:3558:5)
    at parseClass (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:3703:24)
    at parseStatement (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:2603:14)
    at parseTopLevel (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:2567:18)
    at Object.exports.parse (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:51:12)
    at module.exports (/usr/share/atom/resources/app/node_modules/babel-core/lib/babel/helpers/parse.js:18:21)
```

### Commands

```
     -0:49.9 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.4
autocomplete-glsl, v0.2.3
language-glsl, v2.0.1
language-liquid, v0.4.0
language-opencl, v0.1.1
language-purescript, v0.6.1
language-shadercode, v2.0.0
language-shadercode-shaderlab, v2.0.1

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-07-06 18:23
Your Atom version if very old. Therefore I will close this ticket for now. If the problem is still happening for you with the current release please comment here (and it can be reopened) or fill a new ticket. Thanks.

**Closed by dirk-thomas** 2016-07-06 18:23 UTC
