### ISSUE TITLE
Font Size Increase

### ISSUE THREAD

**Issue by mayowa** [sharvil/api-docs#10] opened 2015-09-04 19:14 UTC
When an API-Doc tab is opened, the font size of text in Tab headers and the tree view is increased significantly. Closing the API-Doc tab returns the fonts to normal, but closes the right pane including other open tabs in the pane.

**Before**
![selection_023](https://cloud.githubusercontent.com/assets/571373/9692504/690af6ba-5341-11e5-8648-7968094f1e60.png)

**After**
![selection_024](https://cloud.githubusercontent.com/assets/571373/9692514/7626610e-5341-11e5-9fd4-e79ea6f6ebc5.png)

**Comment by GFlorio** [comment] 2015-09-07 16:00
I can confirm the change in font size and the closing of other open tabs in right pane.
Using plain Ubuntu 15.04.

**Comment by sharvil** [comment] 2015-09-07 17:45
Sorry folks, I know this is annoying but we have this behavior because I can't use a shadow DOM to isolate CSS changes to just the api-docs tab. Doing so would result in Atom crashing (see https://github.com/atom/atom/issues/5388).

This bug is blocked by https://github.com/atom/atom/pull/7877 getting merged and deployed widely.

**Comment by sharvil** [comment] 2016-02-08 00:18
This is now fixed in api-docs 0.0.4.

**Closed by sharvil** 2016-02-08 00:18 UTC

**Comment by mayowa** [comment] 2016-02-12 13:05
Works like a charm. Thanks you!!
