### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by melanholly** [sharvil/api-docs#11] opened 2015-09-11 09:26 UTC
Hi there this is my first issue creation for atom so I guess it might be a bit less informative. 
The plugin is good but have some bad sides as not opening new column only for documentation. 

1. open a document and browse documentation in second column
2. open third column and try to browse the documentation again

**Atom Version**: 1.0.11
**System**: Microsoft Windows Server 2008 R2 Enterprise 
**Thrown From**: [api-docs](https://github.com/sharvil/api-docs) package, v0.0.3

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\src\item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
  at ItemRegistry.module.exports.ItemRegistry.addItem (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\src\item-registry.js:11:15)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\src\pane-container.js:351:25)
  at C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\src\pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\src\pane.js:345:20)
  at Pane.module.exports.Pane.activateItem (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\src\pane.js:313:14)
  at DocView.attached (C:\Users\Kiril\.atom\packages\api-docs\src\doc_view.js:115:18)
  at space-pen-div.View.element.attached (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:51:55)
  at atom-pane.PaneElement.activeItemChanged (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\src\pane-element.js:150:24)
  at Emitter.module.exports.Emitter.emit (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\src\pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\src\pane.js:314:21)
  at C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\src\workspace.js:489:16
  at _fulfilled (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:794:54)
  at self.promiseDispatch.done (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:823:30)
  at Promise.promise.promiseDispatch (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:756:13)
  at C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:817:14
  at flush (C:\Users\Kiril\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\q\q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:56.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:55.8.0 api-docs:search-under-cursor (atom-text-editor.editor.is-focused)
     -0:54.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:47.2.0 pane:split-right (div.api-docs-doc.api-docs-theme-light)
     -0:44.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:43.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:38.2.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:35 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:29.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:29.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:26.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:24.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:24.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:23.5.0 api-docs:search-under-cursor (atom-text-editor.editor.is-focused)
     -0:22.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "open-on-github"
    ]
  },
  "api-docs": {
    "jquery": true,
    "php": true
  }
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.3
highlight-selected, v0.10.1
Remote-FTP, v0.7.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-07-06 18:28
The Atom version in this issue is pretty old. Therefore I will close this ticket for now. If the problem is still happening for you with the current release please comment here (and it can be reopened) or fill a new ticket. Thanks.

**Closed by dirk-thomas** 2016-07-06 18:28 UTC
